# Generated by Django 5.1.7 on 2025-03-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('아동ID', models.CharField(max_length=10, unique=True)),
                ('나이', models.IntegerField()),
                ('성별', models.CharField(max_length=10)),
                ('출석패턴', models.CharField(max_length=20)),
                ('감정상태', models.CharField(max_length=20)),
                ('외상유무', models.CharField(max_length=10)),
                ('낮잠중깸', models.CharField(max_length=10)),
                ('부정언어표현', models.CharField(max_length=10)),
                ('그림감정', models.CharField(max_length=10)),
                ('이상행동점수', models.FloatField()),
                ('보호자형태', models.CharField(max_length=20)),
                ('소득수준', models.CharField(max_length=10)),
                ('보호자정서상태', models.CharField(max_length=10)),
                ('연락빈도', models.CharField(max_length=10)),
                ('보호자공격성', models.CharField(max_length=10)),
                ('과거신고이력', models.CharField(max_length=10)),
                ('가정환경점수', models.FloatField()),
                ('형제자매수', models.IntegerField()),
                ('신체접촉반응', models.CharField(max_length=10)),
                ('교사관찰메모', models.TextField()),
            ],
        ),
    ]
