# Generated by Django 5.1.7 on 2025-03-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childabuse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('입력시간', models.DateTimeField(auto_now_add=True)),
                ('나이', models.IntegerField()),
                ('성별', models.CharField(max_length=10)),
                ('출석패턴', models.CharField(max_length=20)),
                ('부정언어표현', models.CharField(max_length=10)),
                ('보호자공격성', models.CharField(max_length=10)),
                ('예측결과', models.CharField(max_length=50)),
            ],
        ),
    ]
