# Generated by Django 5.1.6 on 2025-03-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("childabuse", "0003_rename_나이_childobservation_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="childobservation",
            name="contact_reaction",
            field=models.CharField(
                choices=[
                    ("선호", "선호"),
                    ("중립", "중립"),
                    ("회피", "회피"),
                    ("공포", "공포"),
                ],
                default="중립",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="childobservation",
            name="emotional_state",
            field=models.CharField(
                choices=[("안정", "안정"), ("우울", "우울"), ("불안", "불안")],
                default="안정",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="childobservation",
            name="income_level",
            field=models.CharField(
                choices=[("낮음", "낮음"), ("중간", "중간"), ("높음", "높음")],
                default="중간",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="childobservation",
            name="sibling",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="childobservation",
            name="attendance",
            field=models.CharField(
                choices=[
                    ("정상", "정상"),
                    ("자주결석", "자주결석"),
                    ("불규칙", "불규칙"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="childobservation",
            name="gender",
            field=models.CharField(
                choices=[("남아", "남아"), ("여아", "여아")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="childobservation",
            name="negative_language",
            field=models.CharField(
                choices=[("낮음", "낮음"), ("중간", "중간"), ("높음", "높음")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="childobservation",
            name="parental_aggression",
            field=models.CharField(
                choices=[("없음", "없음"), ("약함", "약함"), ("강함", "강함")],
                max_length=10,
            ),
        ),
    ]
