# Generated by Django 5.1.6 on 2025-03-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("childabuse", "0004_childobservation_contact_reaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionhistory",
            name="predicted_prob",
            field=models.FloatField(default=0.0),
        ),
    ]
